site_name: CodeAlag
theme:
  name: material
  copyright: Copyright &copy; 2021 CodeAlag
  extra:
    generator: false
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
