site_name: CodeAlag
site_url: https://codealag.github.io/
site_author: CodeAlag
site_description: Programming concepts taught by non cs developers
copyright: Copyright &copy; 2021 CodeAlag

theme:
  name: 'material'
  language: 'en'
  docs_dir: Docs
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    
# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra:
  generator: 'false'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/codealag'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/codealag'

# Page tree	
nav:
  - 'Home': 'index.md'
  - 'Data Structures & Algorithms':
    - 'Introduction': 'data-structures-and-algorithms/introduction.md'
    - 'Data Types': 'data-structures-and-algorithms/data-types.md'
    - 'Memory Allocation': 'data-structures-and-algorithms/memory-allocation.md'
    - 'Fixed Array': 'data-structures-and-algorithms/fixed-array.md'
    - 'Dynamic Array': 'data-structures-and-algorithms/dynamic-array.md'
